-- CATCHY telemetry-service baseline schema.
-- Portable SQL: runs unchanged on H2 (PostgreSQL mode) and PostgreSQL.
-- Privacy: no column anywhere holds raw cache keys, cached values, patient data, tokens or credentials.

CREATE TABLE project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80)  NOT NULL,
    name_lower  VARCHAR(80)  NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_project_name_lower UNIQUE (name_lower)
);

CREATE TABLE application_service (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT       NOT NULL,
    name              VARCHAR(63)  NOT NULL,
    display_name      VARCHAR(120) NOT NULL,
    environment       VARCHAR(31)  NOT NULL,
    description       VARCHAR(500),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    last_telemetry_at TIMESTAMP WITH TIME ZONE,
    region_count      INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_application_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT uq_application_name_env UNIQUE (name, environment)
);
CREATE INDEX idx_application_project ON application_service (project_id);

-- Only the SHA-256 hash and a short non-secret prefix of an API key are stored.
CREATE TABLE application_api_key (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT       NOT NULL,
    label          VARCHAR(120) NOT NULL,
    key_prefix     VARCHAR(16)  NOT NULL,
    key_hash       VARCHAR(64)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at   TIMESTAMP WITH TIME ZONE,
    revoked_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_api_key_application FOREIGN KEY (application_id) REFERENCES application_service (id),
    CONSTRAINT uq_api_key_hash UNIQUE (key_hash)
);
CREATE INDEX idx_api_key_application ON application_api_key (application_id);

-- Safe event metadata only (key fingerprints, never raw keys or values).
CREATE TABLE cache_telemetry_event (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id             BIGINT       NOT NULL,
    cache_region               VARCHAR(63)  NOT NULL,
    instance_id                VARCHAR(80),
    event_timestamp            TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    action                     VARCHAR(32)  NOT NULL,
    key_fingerprint            VARCHAR(80),
    reason                     VARCHAR(400),
    policy                     VARCHAR(8)   NOT NULL,
    frequency                  BIGINT       NOT NULL,
    last_access_age_ms         BIGINT       NOT NULL,
    remaining_ttl_ms           BIGINT       NOT NULL,
    estimated_entry_size_bytes BIGINT       NOT NULL,
    cache_size_before          INTEGER      NOT NULL,
    cache_size_after           INTEGER      NOT NULL,
    memory_before_bytes        BIGINT       NOT NULL,
    memory_after_bytes         BIGINT       NOT NULL,
    value_returned             BOOLEAN      NOT NULL,
    severity                   VARCHAR(16)  NOT NULL,
    latency_ms                 DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_event_application FOREIGN KEY (application_id) REFERENCES application_service (id)
);
CREATE INDEX idx_event_app_region_ts ON cache_telemetry_event (application_id, cache_region, event_timestamp);
CREATE INDEX idx_event_app_id ON cache_telemetry_event (application_id, id);

-- Every received cumulative snapshot. "latest" marks the newest row per (application, region, instance).
CREATE TABLE cache_metrics_snapshot (
    id                                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id                        BIGINT       NOT NULL,
    cache_region                          VARCHAR(63)  NOT NULL,
    instance_id                           VARCHAR(80)  NOT NULL,
    captured_at                           TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at                           TIMESTAMP WITH TIME ZONE NOT NULL,
    latest                                BOOLEAN      NOT NULL,
    risk_level                            VARCHAR(16)  NOT NULL,
    active_policy                         VARCHAR(8)   NOT NULL,
    hits                                  BIGINT       NOT NULL,
    misses                                BIGINT       NOT NULL,
    puts                                  BIGINT       NOT NULL,
    removes                               BIGINT       NOT NULL,
    clears                                BIGINT       NOT NULL,
    evictions                             BIGINT       NOT NULL,
    expirations                           BIGINT       NOT NULL,
    cache_size                            INTEGER      NOT NULL,
    capacity                              INTEGER      NOT NULL,
    estimated_memory_usage_bytes          BIGINT       NOT NULL,
    maximum_memory_bytes                  BIGINT       NOT NULL,
    lru_evictions                         BIGINT       NOT NULL,
    lfu_evictions                         BIGINT       NOT NULL,
    evictions_due_to_entry_limit          BIGINT       NOT NULL,
    evictions_due_to_memory_limit         BIGINT       NOT NULL,
    average_get_latency_ms                DOUBLE PRECISION NOT NULL,
    average_put_latency_ms                DOUBLE PRECISION NOT NULL,
    source_calls_avoided                  BIGINT       NOT NULL,
    telemetry_events_sent                 BIGINT       NOT NULL,
    telemetry_events_failed               BIGINT       NOT NULL,
    telemetry_failure_streak              INTEGER      NOT NULL,
    l1_hits                               BIGINT       NOT NULL,
    victim_hits                           BIGINT       NOT NULL,
    source_misses                         BIGINT       NOT NULL,
    victim_evictions                      BIGINT       NOT NULL,
    victim_enabled                        BOOLEAN      NOT NULL,
    victim_size                           INTEGER      NOT NULL,
    victim_capacity                       INTEGER      NOT NULL,
    refreshes_started                     BIGINT       NOT NULL,
    concurrent_requests_coalesced         BIGINT       NOT NULL,
    source_calls_avoided_by_stampede_shield BIGINT     NOT NULL,
    refresh_failures                      BIGINT       NOT NULL,
    source_calls                          BIGINT       NOT NULL,
    source_errors                         BIGINT       NOT NULL,
    stale_served                          BIGINT       NOT NULL,
    stale_corrections                     BIGINT       NOT NULL,
    stale_data_violations                 BIGINT       NOT NULL,
    default_ttl_ms                        BIGINT       NOT NULL,
    last_policy_change_at                 TIMESTAMP WITH TIME ZONE,
    recent_minutes                        INTEGER      NOT NULL,
    recent_hits                           BIGINT       NOT NULL,
    recent_misses                         BIGINT       NOT NULL,
    recent_puts                           BIGINT       NOT NULL,
    recent_evictions                      BIGINT       NOT NULL,
    recent_expirations                    BIGINT       NOT NULL,
    has_shadow                            BOOLEAN      NOT NULL,
    shadow_requests                       BIGINT       NOT NULL,
    shadow_window_requests                INTEGER      NOT NULL,
    shadow_lru_hit_rate                   DOUBLE PRECISION NOT NULL,
    shadow_lfu_hit_rate                   DOUBLE PRECISION NOT NULL,
    shadow_top_key_concentration          DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_snapshot_application FOREIGN KEY (application_id) REFERENCES application_service (id)
);
CREATE INDEX idx_snapshot_series ON cache_metrics_snapshot (application_id, cache_region, instance_id, captured_at);
CREATE INDEX idx_snapshot_latest ON cache_metrics_snapshot (latest, application_id);
CREATE INDEX idx_snapshot_captured ON cache_metrics_snapshot (captured_at);

-- Latest Policy Arena result per (application, region).
CREATE TABLE cache_policy_recommendation (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT       NOT NULL,
    cache_region         VARCHAR(63)  NOT NULL,
    current_policy       VARCHAR(8)   NOT NULL,
    recommended_policy   VARCHAR(8)   NOT NULL,
    action               VARCHAR(8)   NOT NULL,
    summary              VARCHAR(120) NOT NULL,
    lru_shadow_hit_rate  DOUBLE PRECISION NOT NULL,
    lfu_shadow_hit_rate  DOUBLE PRECISION NOT NULL,
    improvement_percent  DOUBLE PRECISION NOT NULL,
    confidence           INTEGER      NOT NULL,
    reason               VARCHAR(1000) NOT NULL,
    ai_explanation       VARCHAR(2000),
    sample_size          BIGINT       NOT NULL,
    minimum_sample_met   BOOLEAN      NOT NULL,
    cooldown_active      BOOLEAN      NOT NULL,
    cooldown_ends_at     TIMESTAMP WITH TIME ZONE,
    approval_required    BOOLEAN      NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_recommendation_application FOREIGN KEY (application_id) REFERENCES application_service (id),
    CONSTRAINT uq_recommendation_region UNIQUE (application_id, cache_region)
);

CREATE TABLE policy_change_request (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    BIGINT       NOT NULL,
    cache_region      VARCHAR(63)  NOT NULL,
    current_policy    VARCHAR(8)   NOT NULL,
    requested_policy  VARCHAR(8)   NOT NULL,
    reason            VARCHAR(500),
    status            VARCHAR(16)  NOT NULL,
    requested_by      VARCHAR(64)  NOT NULL,
    decided_by        VARCHAR(64),
    decision_note     VARCHAR(500),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_at        TIMESTAMP WITH TIME ZONE,
    applied_at        TIMESTAMP WITH TIME ZONE,
    recommendation_id BIGINT,
    CONSTRAINT fk_policy_request_application FOREIGN KEY (application_id) REFERENCES application_service (id)
);
CREATE INDEX idx_policy_request_app ON policy_change_request (application_id, id);
CREATE INDEX idx_policy_request_region ON policy_change_request (application_id, cache_region, status);

-- Desired tuning set by an administrator; delivered to the SDK through /telemetry/control.
CREATE TABLE region_config_override (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id       BIGINT       NOT NULL,
    cache_region         VARCHAR(63)  NOT NULL,
    maximum_entries      BIGINT,
    maximum_memory_bytes BIGINT,
    default_ttl_ms       BIGINT,
    tuning_version       BIGINT       NOT NULL,
    applied_version      BIGINT       NOT NULL,
    reason               VARCHAR(300),
    updated_by           VARCHAR(64)  NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_config_application FOREIGN KEY (application_id) REFERENCES application_service (id),
    CONSTRAINT uq_config_region UNIQUE (application_id, cache_region)
);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    actor          VARCHAR(80)  NOT NULL,
    actor_role     VARCHAR(16)  NOT NULL,
    action         VARCHAR(40)  NOT NULL,
    target_type    VARCHAR(32),
    target_id      VARCHAR(80),
    application_id BIGINT,
    details        VARCHAR(1000),
    outcome        VARCHAR(16)  NOT NULL
);
CREATE INDEX idx_audit_occurred ON audit_log (occurred_at);
CREATE INDEX idx_audit_application ON audit_log (application_id, id);

-- Demo users. password_hash is NULL when no password was configured (demo-login only).
CREATE TABLE user_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(40)  NOT NULL,
    password_hash VARCHAR(100),
    role          VARCHAR(16)  NOT NULL,
    CONSTRAINT uq_user_username UNIQUE (username)
);
