package com.acentra.catchy.telemetry.service;

/** The audited actions listed in docs/api.md. */
public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PROJECT_CREATED,
    APPLICATION_CREATED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    POLICY_CHANGE_REQUESTED,
    POLICY_CHANGE_APPROVED,
    POLICY_CHANGE_REJECTED,
    POLICY_CHANGE_APPLIED,
    CONFIG_CHANGE_REQUESTED,
    CONFIG_CHANGE_APPLIED,
    RECOMMENDATION_EVALUATED,
    SIMULATION_RUN,
    TELEMETRY_REJECTED,
    ACCESS_DENIED
}
