// Generated by scripts/generate-circuit.mjs — do not edit.
// Regenerate with `npm run generate:circuit`; `node scripts/generate-circuit.mjs --check` verifies it.
// Seed 20260930: 1440x900 board, 24 px grid, 40 traces (16 electron lanes), 6 pads, 29 vias, 3 ICs.

export interface CircuitCircle {
  readonly x: number;
  readonly y: number;
  readonly r: number;
}

export interface CircuitRect {
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

/** A copper trace; `d` is an SVG path in board pixels. */
export interface CircuitStaticTrace {
  readonly d: string;
  readonly lane: false;
}

/** A trace that carries an electron: one lap takes `durationS`, starting `delayS` into it. */
export interface CircuitLaneTrace {
  readonly d: string;
  readonly lane: true;
  readonly durationS: number;
  readonly delayS: number;
}

export type CircuitTrace = CircuitStaticTrace | CircuitLaneTrace;

/** An IC body with its pin rows, pin-1 dot and silkscreen label. */
export interface CircuitIc extends CircuitRect {
  readonly label: { readonly text: string; readonly x: number; readonly y: number };
  readonly dot: CircuitCircle;
  readonly pins: readonly CircuitRect[];
}

export interface Circuit {
  readonly width: number;
  readonly height: number;
  readonly grid: number;
  readonly traces: readonly CircuitTrace[];
  readonly pads: readonly CircuitCircle[];
  readonly vias: readonly CircuitCircle[];
  readonly ics: readonly CircuitIc[];
}

export const CIRCUIT: Circuit = {
  width: 1440,
  height: 900,
  grid: 24,
  traces: [
    { d: 'M1056 184V-12', lane: false },
    { d: 'M1032 184V-12', lane: false },
    { d: 'M240 136V-12', lane: false },
    { d: 'M216 136V-12', lane: false },
    { d: 'M1008 680V912', lane: false },
    { d: 'M1032 680V912', lane: false },
    { d: 'M1056 680V912', lane: false },
    { d: 'M1272 912V576L1296 552H1452', lane: true, durationS: 7.4, delayS: 0.1 },
    { d: 'M1296 912V600L1320 576H1452', lane: true, durationS: 7.6, delayS: 5.1 },
    { d: 'M1320 912V624L1344 600H1452', lane: false },
    { d: 'M1344 912V648L1368 624H1452', lane: false },
    { d: 'M1452 528H864L840 504V216L816 192H744L720 168V-12', lane: true, durationS: 11.4, delayS: 2.9 },
    { d: 'M1452 504H888L864 480V192L840 168H768L744 144V-12', lane: true, durationS: 11.7, delayS: 10.3 },
    { d: 'M672 -12V744L648 768H552L528 792V912', lane: true, durationS: 10.2, delayS: 5.4 },
    { d: 'M480 912V768L528 720V432L504 408H384L360 384V-12', lane: true, durationS: 10.9, delayS: 1.7 },
    { d: 'M-12 72H120L168 24V-12', lane: false },
    { d: 'M-12 96H144L192 48V-12', lane: false },
    { d: 'M1452 480H984L936 432V-12', lane: true, durationS: 10.9, delayS: 7.9 },
    { d: 'M240 912V624L216 600H-12', lane: false },
    { d: 'M264 912V600L240 576H-12', lane: true, durationS: 7.9, delayS: 3.2 },
    { d: 'M288 912V576L264 552H-12', lane: true, durationS: 7.9, delayS: 0.1 },
    { d: 'M1452 360H1368L1344 336V240L1320 216H1296L1272 192V-12', lane: false },
    { d: 'M1452 384H1344L1320 360V264L1296 240H1272L1248 216V-12', lane: true, durationS: 7.5, delayS: 4.5 },
    { d: 'M1452 408H1320L1296 384V288L1272 264H1248L1224 240V-12', lane: true, durationS: 7.8, delayS: 1.7 },
    { d: 'M1452 336H1392L1368 312V216L1344 192H1320L1296 168V-12', lane: false },
    { d: 'M-12 432H408L432 456V528L408 552H384L360 576V912', lane: true, durationS: 10, delayS: 8.7 },
    { d: 'M-12 672H144L168 696V744L144 768V912', lane: true, durationS: 7.2, delayS: 3.3 },
    { d: 'M1368 912V696L1392 672H1452', lane: false },
    { d: 'M-12 816H72L96 840V912', lane: false },
    { d: 'M888 912V744L864 720H792L768 696V528L792 504V408L768 384H720L696 360V-12', lane: true, durationS: 10.5, delayS: 0.8 },
    { d: 'M-12 624H192L216 648V744L192 768V912', lane: true, durationS: 8.1, delayS: 5.6 },
    { d: 'M1320 -12V96L1344 120H1452', lane: false },
    { d: 'M1344 -12V72L1368 96H1452', lane: false },
    { d: 'M1368 -12V48L1392 72H1452', lane: false },
    { d: 'M504 -12V72L552 120V288L576 312H624', lane: false },
    { d: 'M-12 336H312', lane: false },
    { d: 'M-12 408H336', lane: false },
    { d: 'M1248 912V576', lane: false },
    { d: 'M576 -12V168L600 192H624', lane: false },
    { d: 'M1452 456H1104L1080 432V360', lane: true, durationS: 7.1, delayS: 2.4 },
  ],
  pads: [
    { x: 624, y: 312, r: 5 },
    { x: 312, y: 336, r: 5 },
    { x: 336, y: 408, r: 5 },
    { x: 1248, y: 576, r: 5 },
    { x: 624, y: 192, r: 5 },
    { x: 1080, y: 360, r: 5 },
  ],
  vias: [
    { x: 1296, y: 552, r: 3.5 },
    { x: 1344, y: 648, r: 3.5 },
    { x: 864, y: 528, r: 3.5 },
    { x: 744, y: 192, r: 3.5 },
    { x: 864, y: 480, r: 3.5 },
    { x: 864, y: 192, r: 3.5 },
    { x: 552, y: 768, r: 3.5 },
    { x: 504, y: 408, r: 3.5 },
    { x: 384, y: 408, r: 3.5 },
    { x: 168, y: 24, r: 3.5 },
    { x: 1344, y: 336, r: 3.5 },
    { x: 1344, y: 240, r: 3.5 },
    { x: 1296, y: 240, r: 3.5 },
    { x: 1248, y: 264, r: 3.5 },
    { x: 1320, y: 192, r: 3.5 },
    { x: 432, y: 456, r: 3.5 },
    { x: 432, y: 528, r: 3.5 },
    { x: 168, y: 696, r: 3.5 },
    { x: 72, y: 816, r: 3.5 },
    { x: 792, y: 408, r: 3.5 },
    { x: 696, y: 360, r: 3.5 },
    { x: 192, y: 624, r: 3.5 },
    { x: 192, y: 768, r: 3.5 },
    { x: 1344, y: 120, r: 3.5 },
    { x: 1344, y: 72, r: 3.5 },
    { x: 552, y: 120, r: 3.5 },
    { x: 576, y: 312, r: 3.5 },
    { x: 576, y: 168, r: 3.5 },
    { x: 1080, y: 432, r: 3.5 },
  ],
  ics: [
    {
      x: 1008,
      y: 192,
      w: 144,
      h: 96,
      label: { text: 'U17', x: 1160, y: 244 },
      dot: { x: 1017, y: 279, r: 3 },
      pins: [
        { x: 1017, y: 184, w: 6, h: 8 }, { x: 1017, y: 288, w: 6, h: 8 }, { x: 1029, y: 184, w: 6, h: 8 }, { x: 1029, y: 288, w: 6, h: 8 },
        { x: 1041, y: 184, w: 6, h: 8 }, { x: 1041, y: 288, w: 6, h: 8 }, { x: 1053, y: 184, w: 6, h: 8 }, { x: 1053, y: 288, w: 6, h: 8 },
        { x: 1065, y: 184, w: 6, h: 8 }, { x: 1065, y: 288, w: 6, h: 8 }, { x: 1077, y: 184, w: 6, h: 8 }, { x: 1077, y: 288, w: 6, h: 8 },
        { x: 1089, y: 184, w: 6, h: 8 }, { x: 1089, y: 288, w: 6, h: 8 }, { x: 1101, y: 184, w: 6, h: 8 }, { x: 1101, y: 288, w: 6, h: 8 },
        { x: 1113, y: 184, w: 6, h: 8 }, { x: 1113, y: 288, w: 6, h: 8 }, { x: 1125, y: 184, w: 6, h: 8 }, { x: 1125, y: 288, w: 6, h: 8 },
        { x: 1137, y: 184, w: 6, h: 8 }, { x: 1137, y: 288, w: 6, h: 8 },
      ],
    },
    {
      x: 144,
      y: 144,
      w: 144,
      h: 96,
      label: { text: 'U13', x: 296, y: 196 },
      dot: { x: 153, y: 231, r: 3 },
      pins: [
        { x: 153, y: 136, w: 6, h: 8 }, { x: 153, y: 240, w: 6, h: 8 }, { x: 165, y: 136, w: 6, h: 8 }, { x: 165, y: 240, w: 6, h: 8 },
        { x: 177, y: 136, w: 6, h: 8 }, { x: 177, y: 240, w: 6, h: 8 }, { x: 189, y: 136, w: 6, h: 8 }, { x: 189, y: 240, w: 6, h: 8 },
        { x: 201, y: 136, w: 6, h: 8 }, { x: 201, y: 240, w: 6, h: 8 }, { x: 213, y: 136, w: 6, h: 8 }, { x: 213, y: 240, w: 6, h: 8 },
        { x: 225, y: 136, w: 6, h: 8 }, { x: 225, y: 240, w: 6, h: 8 }, { x: 237, y: 136, w: 6, h: 8 }, { x: 237, y: 240, w: 6, h: 8 },
        { x: 249, y: 136, w: 6, h: 8 }, { x: 249, y: 240, w: 6, h: 8 }, { x: 261, y: 136, w: 6, h: 8 }, { x: 261, y: 240, w: 6, h: 8 },
        { x: 273, y: 136, w: 6, h: 8 }, { x: 273, y: 240, w: 6, h: 8 },
      ],
    },
    {
      x: 984,
      y: 600,
      w: 144,
      h: 72,
      label: { text: 'U15', x: 1136, y: 640 },
      dot: { x: 993, y: 663, r: 3 },
      pins: [
        { x: 993, y: 592, w: 6, h: 8 }, { x: 993, y: 672, w: 6, h: 8 }, { x: 1005, y: 592, w: 6, h: 8 }, { x: 1005, y: 672, w: 6, h: 8 },
        { x: 1017, y: 592, w: 6, h: 8 }, { x: 1017, y: 672, w: 6, h: 8 }, { x: 1029, y: 592, w: 6, h: 8 }, { x: 1029, y: 672, w: 6, h: 8 },
        { x: 1041, y: 592, w: 6, h: 8 }, { x: 1041, y: 672, w: 6, h: 8 }, { x: 1053, y: 592, w: 6, h: 8 }, { x: 1053, y: 672, w: 6, h: 8 },
        { x: 1065, y: 592, w: 6, h: 8 }, { x: 1065, y: 672, w: 6, h: 8 }, { x: 1077, y: 592, w: 6, h: 8 }, { x: 1077, y: 672, w: 6, h: 8 },
        { x: 1089, y: 592, w: 6, h: 8 }, { x: 1089, y: 672, w: 6, h: 8 }, { x: 1101, y: 592, w: 6, h: 8 }, { x: 1101, y: 672, w: 6, h: 8 },
        { x: 1113, y: 592, w: 6, h: 8 }, { x: 1113, y: 672, w: 6, h: 8 },
      ],
    },
  ],
};
